language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    # - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

script:
    ./gradlew clean assemble --stacktrace

jdk:
    - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false
  slack:
    secure: gxWIlm1gLCI8/OFlA4ucj8bUvwlzKZNRBqhaQZHUUMcd+BIqOHILnT7lDz0NwMGbaVbGrYLbG6pd9RcafUUVXkFYmK/SHEpHCMvpKGiJlEOZ+u06QSNVGrjb0Bzo74o3Tk1FKlQyKpUi8gtYe4ZD2r8JBiWC07z5OYdgC1sAEGP7YQG7MrCMa9Qs7Vtkk1S8priQ8JeWA4ufF1WR13bVhWxqozhVC8bkG1UZWQ2p0psGUihG5N1HhMrkFSInINCGK1G/Gsq8ql1zK7LkWbcQExowwLfc/YIq7wu9f1LCdPuQFyt6/5CeU3SVIE1OgCMg2FyQVeySpuvg0GlneLi2VWymnSUM0czxnD40xM8G0LsxpeZj34CKk12AfDUo746YMadQu2O/oy3Gq0doNxD2IfAiR+RKb1euCfgvaK2ydfXfZNCHbE+3aSb/yXh4Obc3eNgeRnFKdAj440cb0TIKGAUsHYerYfti3UeaQrOQtVw8Bj6+94px3Ch8gReBBYYatmM0LIJljtcMcFx4tuq9SMCO1vkFR5lHOAwLpgQUPfq5FH/QkWa4d1613TNQf7EOKEDtxbOemKZd72M+xVDjxcWLSP7GqixCpG0jKNwUgnTkvK+ThdTHhEza9COYwW+fX9oWFXXZHA3Z0m22Bojyvq3/SKTAADWyS1VX+jXzt7M=

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
